### ISSUE TITLE
onStopTrackingTouch listener method

### ISSUE THREAD

**Issue by ardevd** [feeeei/CircleSeekbar#12]
Hi!

I would like to update a value when the user releases the seekbar but it doesnt seem like the onStopTrackingTouch is implemented in the CircleSeekBar.OnSeekBarChangeListener(). Or am I missing something?

**Comment by qiantao94** [comment]
You can `setOnTouchListener` and listen `event.action == MotionEvent.ACTION_UP`

**Comment by ardevd** [comment]
Awesome, thanks! That worked just fine!
