### ISSUE TITLE
A  program about setCurProgress

### ISSUE THREAD

**Issue by KinsMan2015** [feeeei/CircleSeekbar#2]
![image](https://cloud.githubusercontent.com/assets/13571564/11386991/916b226e-9361-11e5-826d-80cb71ecce42.png)   I  don't  know  why this progress doesn't update

**Comment by KinsMan2015** [comment]
if  i  set this code  when the fragment onCreateView ,it is right

**Comment by feeeei** [comment]
you can try  
mCircleSeekbar.setCurProcess(20);
mCircleSeekbar.postInvalidate();

**Comment by KinsMan2015** [comment]
Thank you very much
2015年11月25日 17:03，"feeeei" notifications@github.com写道：

**Comment by KinsMan2015** [comment]
it is not success   i try      mCircleSeekBar.invalidate();     failed as well

**Comment by ssthouse** [comment]
same problem, Is there a solution now?

**Comment by KinsMan2015** [comment]
util now,No.U can see the source code.Try ！I believe u. 发自网易邮箱大师 On 2016-04-21 18:22 , ssthouse Wrote: same problem, Is there a solution now? — You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub

**Comment by ssthouse** [comment]
ok I'll try _(:з」∠)_ 
thx  anyway!
