### ISSUE TITLE
please add an attribute that can prevent it from over-scrolling

### ISSUE THREAD

**Issue by hwding** [feeeei/CircleSeekbar#5]
it's hard to scroll the bar to 0 or 100 precisely
i want it to stuck to the start point when i scroll it to 100 or 0
that means it can only scroll only one circle
please help, thanks!

@feeeei 求功能支持，能够激活一种属性将scroll限定在一圈之内。

**Comment by Polyterative** [comment]
Same for me

**Comment by feeeei** [comment]
I write a new attribute wheel_scroll_only_one_circle to support this issue in v1.1.0

sorry , I have no idea before

**Comment by hwding** [comment]
@feeeei you did great work, thank you!
