### ISSUE TITLE
when using setCurProcess(), the pointer won't change its position.

### ISSUE THREAD

**Issue by hwding** [feeeei/CircleSeekbar#6]
when using setCurProcess(), the reached part change but the pointer won't change its position.
hope to fix this.

**Comment by feeeei** [comment]
so sorry，才看到消息

可是我这边并没有出现这个问题啊，用download示例测试curProcess，值一直都是正确的
能提供点更详细的信息么？

**Comment by hwding** [comment]
@feeeei 
值是会改变但是pointer并没有变动位置。
如下图：
![screenshot_20160726-005044](https://cloud.githubusercontent.com/assets/15152879/17109614/4c00180e-52cb-11e6-8661-a2cca0ab33be.png)
注意右侧的circleSeekBar在改变值的时候并没有变动pointer的位置。

**Comment by feeeei** [comment]
谢谢~~
这个问题我刚刚已经修复了
你可以尝试用 v1.0.4 版再试一下~

**Comment by hwding** [comment]
@feeeei 感谢.
