### ISSUE TITLE
使用1.0.4版本，锚点(起始圆点)mWheelCurX,mWheelCurY 起始坐标的问题

### ISSUE THREAD

**Issue by AsherYang** [feeeei/CircleSeekbar#7]
1、问题：
在使用过程中发现onMeasure() 一般初始化4次，但在某些手机上有概率初始化2次，这就导致只初始化2次的时候，此时拿到的getWidth() 是为0。这就直接导致mWheelCurX,mWheelCurY计算错误。会出现初始圆点不在正确位置上的问题。

2、解决思路：
a、refreshUnreachedWidth() 方法中计算mUnreachedRadius 时使用getMeasuredWidth()替换原先的getWidth()，因为当onMeasure() 中只初始化2次就规定布局时，getWidth拿到的是0。使用getMeasuredWidth可以确保拿到的mUnreachedRadius每次都是正确的值。
b、在onMeasure()中先refreshUnreachedWidth，再去刷新refreshPosition()，保证mUnreachedRadius 是在下面计算的时候是正确的值。
c、calcXLocationInWheel() 计算X 的坐标时，同样使用getMeasuredWidth()替换getWidth()，原因也是getWidth()为0，计算出来的X坐标永远是0。

3、针对上述问题，不知是否符合本开源项目修改。期待交流。

**Comment by feeeei** [comment]
cool~！
之前在某些情况下也遇到过坐标错乱的问题，当时没有复现，所以不知道去如何修改。
现在新版本 1.1.0 已经换成你说的 getMeasuredWidth 去获取宽高。
谢谢~~~

**Comment by AsherYang** [comment]
Thank you !
在项目中使用到，希望得到容许
