### ISSUE TITLE
CircleSeekBar's wheel is on incorrect position when added in fragment

### ISSUE THREAD

**Issue by craftingmod** [feeeei/CircleSeekbar#8]
If I use circleseekbar in fragment(via onCreateView - inflate), due to incorrect measurewidth,measureheight, the white circle button (aka wheel) goes wrong position, and even if i changed progress by touch, it is just looping which is follwing a small circle.

![incorrect](https://cloud.githubusercontent.com/assets/9389278/19014521/141fec36-882a-11e6-9537-140e6a751503.png)

so, i fixed this problem tempory registering onGlobalLayout and force putting correct measure.

> ```
>     outerBar = (CircleSeekBar) view.findViewById(R.id.outerSeek)
>     ViewTreeObserver vto = outerBar.getViewTreeObserver()
>     vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
>         private boolean updated = false;
>         @Override
>         public void onGlobalLayout() {
>             if(!updated){
>                 // put updated boolean for only once draw
>                 updated = true;
> ```

```
                // getWidth said wrong number. so, should input number.
                int pxCircle = (int)UIUtils.convertDpToPixel(300,context);
                int measureInt = View.MeasureSpec.makeMeasureSpec(pxCircle, View.MeasureSpec.EXACTLY);
                //outerBar.setLayoutParams(params);
                outerBar.measure(measureInt, measureInt);
                // outerBar.refershPosition()
                // cause must correct at first view
                try {
                    // refersh? refresh is correct but :p
                    Method refresh = outerBar.getClass().getDeclaredMethod("refershPosition");
                    refresh.setAccessible(true);
                    refresh.invoke(outerBar);
                } catch (NoSuchMethodException e) {
                    e.printStackTrace();
                } catch (InvocationTargetException e) {
                    e.printStackTrace();
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
                // redraw for correct position.
                outerBar.invalidate();
            }
        }
```

})

![correct](https://cloud.githubusercontent.com/assets/9389278/19014552/1067fa56-882b-11e6-8ceb-cd30c42cd0d3.png)

i don't know why this bug happen, but i believe you can something edit 👍

**Comment by feeeei** [comment]
Thanks so much~
Now,i fix this issue in v1.1.1

**Comment by craftingmod** [comment]
Thanks quick fix :D

**Comment by anuragopenxcell** [comment]
Still facing this issue in v1.1.1 when I dynamically set the layout params of the circular seekbar from global layout change listener.
