### ISSUE TITLE
OnSeekBarChangeListener 连续触发3次，改变一次滑动条值就触发3次

### ISSUE THREAD

**Issue by protectedMan** [feeeei/CircleSeekbar#9]

**Comment by feeeei** [comment]
这一点是因为 onTouch 事件传递的问题
`ACTION_MOVE`与`ACTION_UP`与`ACTION_CANCEL`都会触发
为了通用性，这个地方不能改
不知这个地方会影响到什么么？

**Comment by protectedMan** [comment]
![image](https://cloud.githubusercontent.com/assets/17565737/21175942/a8c2f32c-c21f-11e6-999d-7b5cd079f7e6.png)

- 因为我在此处使用了toast的原因所以才发现改变一次值会调用三次。
- 不过我使用一个变量已经解决了这个问题。

不过还是希望你能解决这个问题，因为如果在此处进行UI操作的话会导致重复调用的问题。

**Comment by feeeei** [comment]
哦... 
Toast 在我的项目里面一般都是全局单例的，所以重复 toast 也不会有问题...
我还是尝试更新了一版 [v1.1.2](https://github.com/feeeei/CircleSeekbar/releases/tag/v1.1.2)
变动在这里[#commit](https://github.com/feeeei/CircleSeekbar/commit/12b2368c5b1637d0dd77149a9d663027d9fb612b)
